### ISSUE TITLE
skale-engine version 0.5.3 regression?

### ISSUE THREAD

**Issue by philippe56** [skale-me/skale-engine#61]
$ skale create dd2bis
create application dd2bis

> skale-engine@0.5.3 preinstall /home/felix/skale/cli/dd2bis/node_modules/.staging/skale-engine-1126d865
> mkdir -p node_modules && echo "module.exports = require('..');" > node_modules/skale-engine.js

dd2bis@0.1.0 /home/felix/skale/cli/dd2bis
`-- skale-engine@0.5.3 
  +-- any-promise@1.3.0 
  +-- bluebird@3.4.0 
  +-- line-trace@1.0.5 
  +-- mkdirp@0.5.1 
  |`-- minimist@0.0.8 
  +-- node-getopt@0.2.3 
  +-- node-uuid@1.4.7 
  +-- thenify@3.2.0 
  +-- websocket-stream@3.1.0 
  | +-- duplexify@3.4.3 
  | | +-- end-of-stream@1.0.0 
  | | | `-- once@1.3.3 
  | | |`-- wrappy@1.0.2 
  | | `-- readable-stream@2.1.3 
  | |   +-- buffer-shims@1.0.0 
  | |   +-- core-util-is@1.0.2 
  | |   +-- isarray@1.0.0 
  | |   +-- process-nextick-args@1.0.7 
  | |   +-- string_decoder@0.10.31 
  | |`-- util-deprecate@1.0.2 
  | +-- inherits@2.0.1 
  | +-- through2@2.0.1 
  | | `-- readable-stream@2.0.6 
  |`-- xtend@4.0.1 
  `-- ws@1.1.0 
    +-- options@0.0.6 
`-- ultron@1.0.2 

Project dd2bis is now ready.
Pleas change directory to dd2bis: "cd dd2bis"
To run your app: "skale run"
To modify your app: edit dd2bis.js

$ cd dd2bis
$ skale run
/home/felix/skale/cli/dd2bis/node_modules/skale-engine/lib/dataset.js:171
                        result = combiner(result, res.data);
                                                     ^
TypeError: Cannot read property 'data' of null
    at taskDone (/home/felix/skale/cli/dd2bis/node_modules/skale-engine/lib/dataset.js:171:33)
    at Object.<anonymous> (/home/felix/skale/cli/dd2bis/node_modules/skale-engine/lib/context.js:129:4)
    at Consumer._transform (/home/felix/skale/cli/dd2bis/node_modules/skale-engine/lib/client.js:120:32)
    at Consumer.Transform._read (_stream_transform.js:167:10)
    at Consumer.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:287:5)
    at Consumer.Writable.write (_stream_writable.js:215:11)
    at FromGrid.ondata (_stream_readable.js:536:20)
    at emitOne (events.js:77:13)

**Comment by mvertes** [comment]
If you perform once `skale run --reset` or `skale stop; skale run`, the problem should disappear. Can you confirm ?

The reason is that you have a skale-server + skale-worker running in version 0.5.2 or before and the master in version 0.5.3. Stopping and restarting force server and worker to run in 0.5.3 as well and fix the problem.

The incompatibility between master in 0.5.3 and server/worker in 0.5.2 is unexpected and was not tested for, otherwise the version would have been set to 0.6.0 instead.

**Comment by philippe56** [comment]
Understood, thank you. One remark, though. For some reason, the first 'skale run --reset' seems to have executed the program twice.

$ cd skale/cli/dd2bis
$ skale run --reset
[ 'Hello world' ]
[ 'Hello world' ]
$ skale run --reset
[ 'Hello world' ]

**Comment by mvertes** [comment]
Closing this one, session server for remote run has evolved a lot, and behaviour changed.
