### ISSUE TITLE
bin/server doesn't use nworker parameter

### ISSUE THREAD

**Issue by mark-bradshaw** [skale-me/skale-engine#82]
It looks like the `nworker` parameter is ignored, and instead the internal variable of the same name is set to the value of the `local` parameter.  It seems like `nworker` should either be removed, or it should be used to set the value of the internal variable instead of `local`.

I'd be happy to provide a PR if that's desired.

**Comment by mvertes** [comment]
Feel free to provide a patch removing `--nworker`. Will be gladly accept it, thanks.

**Comment by mark-bradshaw** [comment]
PR: https://github.com/skale-me/skale-engine/pull/83
